### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by leo60228** [architdate/PKHeX-Plugins#10]
I saw these in GitHub's Explore menu. What do these plugins do?

**Comment by kwsch** [comment]
The readme should be updated with screenshots and a description/summary of features.

PKHeX.Core.AutoMod (class library) provides logic extensions to automatically make/regenerate a legal pkm, using a showdown set or illegal pkm as an input.

Plugins use this logic extension to provide UI to PKHeX.WinForms, with options to legalize tab/sav pkm or bulk import legalized set data from pastebin (etc)

**Comment by architdate** [comment]
The plugins will be slowly documented in the [Wiki](https://github.com/architdate/PKHeX-Plugins/wiki). As of writing this comment, I have documented only 3 pages, however I will slowly be finishing the documentation within the next few days. Will close the issue once the documentation is complete
