### ISSUE TITLE
Can I have an independent setmatchingballs function

### ISSUE THREAD

**Issue by mrhhcc** [architdate/PKHeX-Plugins#101]
Can I have an independent setmatchingballs function.Sorry, my English is terrible

**Comment by Lusamine** [comment]
It already exists in settings and you can also choose one by adding something like "Ball: Moon Ball" to Showdown Sets.

**Comment by mrhhcc** [comment]
I want to setmatching Legality pokemon's ball and retain relearn moves，Thanks for your help

**Comment by mrhhcc** [comment]
> 它已经存在于设置中，您也可以通过在摊牌集中添加类似"球：月亮球"之类的方法来选择一个。

I want to setmatching Legality pokemon's ball and retain relearn moves，Thanks for your help

**Comment by Lusamine** [comment]
You can look at the batch editor commands to target specific encounters.  There isn't a way to only specify ball and also keep relearns unless you use an encounter that is legal.
