### ISSUE TITLE
Zapdos，Moltres，Articuno，Terrakion，Virizion，Cobalion，Keldeo

### ISSUE THREAD

**Issue by mrhhcc** [architdate/PKHeX-Plugins#102]
try to legalize everything in the active box or try to legalize all boxes，Zapdos，Moltres，Articuno，Terrakion，Virizion，Cobalion and Keldeo is Fainting

**Comment by kwsch** [comment]
Please provide more information:

1. What game?
2. Are you using the latest version of PKHeX & this tool?
3. Is the issue that the PKM are listed as "Fainted" when viewing them in-game?

**Comment by mrhhcc** [comment]
> Please provide more information:
> 
> 1. What game?
> 2. Are you using the latest version of PKHeX & this tool?
> 3. Is the issue that the PKM are listed as "Fainted" when viewing them in-game?

1.Pokémon Shield
2.yes
3.yes

**Comment by mrhhcc** [comment]
> 3\. Fainted

can be revived in pokemon center

**Comment by Lusamine** [comment]
I can replicate this with the following steps:
- Take a gen 8 Keldeo from Encounter Database and make it illegal by changing its game of origin.
- Place it in a box.
- Legalize all boxes.
- Use LiveHeX to write current box.

![2021061818170700-B8FAEF4816CAC2B76D11869B05CA7601](https://user-images.githubusercontent.com/30205550/123307277-eafe4b80-d4e7-11eb-9ebd-4a5cd889441d.jpg)

**Comment by kwsch** [comment]
Similar to the Living Dex lacking `Heal()` issue earlier, it appears box legalization is missing the call as well.

https://github.com/architdate/PKHeX-Plugins/blob/f34fd4b1611b920c9d1459bc2d33d4bb780ce468/PKHeX.Core.AutoMod/Enhancements/ModLogic.cs#L220-L238

https://github.com/architdate/PKHeX-Plugins/blob/f34fd4b1611b920c9d1459bc2d33d4bb780ce468/PKHeX.Core.AutoMod/Enhancements/ModLogic.cs#L62-L71
