### ISSUE TITLE
unown form - use user selection

### ISSUE THREAD

**Issue by soaresden** [architdate/PKHeX-Plugins#103]
**Is your feature request related to a problem? Please describe.**

I would like to auto-resolve a "unown" form and not let the plugin choose for me the basic form

**Describe the solution you'd like**
To use user selection of form 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/54243866/123303960-a93cc780-d51e-11eb-9341-ca17c88a8bbd.png)

**Comment by Lusamine** [comment]
You can already do this by appending the form at the end of the Showdown Set.
```
Unown-!
IVs: 14 HP / 6 Atk / 7 Def / 8 SpA / 28 SpD / 13 Spe
Ability: Levitate
Hardy Nature
- Hidden Power [Poison]
```
We recommend you use Showdown Sets to start, but this also works if you have a reasonable Unown already and manually select the form before using Legalize Active Pokemon.

If this does not work for you, please explain what you are doing, and in what game you are doing it in.

**Comment by soaresden** [comment]
HI @Lusamine , 

Thanks for your quick reply
I tried ! 

I'm on Leaf Green.
I took 2 legit one : X and Z just to compare

If I manually edit, it instantly become non legit.
If I auto legalize it, it doesn't keep the form

I also tried your shodown and it's random too :/
I don't know if I do it wrong

here small vid : 
https://streamable.com/o5paf6

**Comment by Lusamine** [comment]
I see what's happening.  Tried importing only ``Unown-K`` to FRLG and it sometimes gives legal K, sometimes gives illegal K, and sometimes gives legal Unown of other forms.

![image](https://user-images.githubusercontent.com/30205550/123321352-7f70aa00-d4f8-11eb-9fd7-d03d1c305fa0.png)
