### ISSUE TITLE
How to change the bid, Sid and trainer name of automatically and legally generated elves to their own instead of pkhex

### ISSUE THREAD

**Issue by shenhongtao66** [architdate/PKHeX-Plugins#104]
https://user-images.githubusercontent.com/62496383/130172865-ae09e618-1904-4143-9b2d-5df9c8bfd8b2.mp4

Cobalt, terrakion and virizion cannot legally flash, and cannot change their bid, Sid and trainer names

**Comment by kwsch** [comment]
Read the wiki.
https://github.com/architdate/PKHeX-Plugins/wiki/Trainer-Data
