### ISSUE TITLE
Auto-legality not working with latest PKhex

### ISSUE THREAD

**Issue by SamBally187** [architdate/PKHeX-Plugins#106]
The auto legality mod isn't working with the latest version of Pkhex that's released yesterday. Can you please fix this?

**Comment by architdate** [comment]
Hi, I am still working on making ALM work with the new BDSP save files and the latest PKHeX. This will take some time to implement. Please be patient :)

Thanks! (I'll pin this issue so others who have the same question can see it)

**Comment by SamBally187** [comment]
> Hi, I am still working on making ALM work with the new BDSP save files and the latest PKHeX. This will take some time to implement. Please be patient :)
> 
> Thanks! (I'll pin this issue so others who have the same question can see it)

Thanks for the quick response! I'll be patient :)
