### ISSUE TITLE
Access denied 

### ISSUE THREAD

**Issue by drewlobel** [architdate/PKHeX-Plugins#107]
So i downloaded it, unblocked it from the properties folder, ran it, and said access was denied from the folder. I used the exe. plz help

**Comment by kwsch** [comment]
where (folder) did you run the setup.exe from? Be sure the exe is in a spot that can create files.

**Comment by drewlobel** [comment]
Same person just on my email: I made the folder on the desktop

On Thu, Nov 25, 2021 at 16:25 Kurt ***@***.***> wrote:

> where (folder) did you run the setup.exe from? Be sure the exe is in a
> spot that can create files.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farchitdate%2FPKHeX-Plugins%2Fissues%2F107%23issuecomment-979474878&data=04%7C01%7C1046403%40locker.lcps.org%7C164b3aa2147047e4523808d9b05a09c0%7C86750b0cee12463db28880f7b2b34689%7C0%7C0%7C637734723015138061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xCS3ohsJTYs0K8Vwn121U%2FMLVfhWoUDyXRvLMG0hW1w%3D&reserved=0>,
> or unsubscribe.
>
-- 
YIS,
Drew S Lobel

**Comment by kwsch** [comment]
Not sure if that's a OneDrive online-only folder; I would try moving it to another folder or USB drive so that the program can write to the local path.

**Comment by drewlobel** [comment]
Ok, I will try that. Thx!

On Thu, Nov 25, 2021 at 16:29 Kurt ***@***.***> wrote:

> Not sure if that's a OneDrive online-only folder; I would try moving it to
> another folder or USB drive so that the program can write to the local path.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farchitdate%2FPKHeX-Plugins%2Fissues%2F107%23issuecomment-979476129&data=04%7C01%7C1046403%40locker.lcps.org%7C918de0ff037a412c722508d9b05a9eeb%7C86750b0cee12463db28880f7b2b34689%7C0%7C0%7C637734725527502912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CC8TN3eHMtUlsB7Qr0hWDUeR4yJJ5PVOp62GeX1EP9w%3D&reserved=0>,
> or unsubscribe.
>
-- 
YIS,
Drew S Lobel

**Comment by architdate** [comment]
No movement on the issue, closing for now. Reopen if the issue persists.
