### ISSUE TITLE
Donphan (M) @ Figy Berry   Ability: Sturdy   EVs: 252 Atk / 4 Def / 252 SpD   Relaxed Nature   IVs: 0 Spe   - Counter   - Gunk Shot   - Play Rough   - Body Slam

### ISSUE THREAD

**Issue by ghost** [architdate/PKHeX-Plugins#111]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why impossible sets cannot be legalized. That should be obvious.
If you encounter a legal pokemon that timed out or didn't legalize properly, upload the `error_log.txt` file present in the same directory as PKHeX

**To Reproduce**
Please provide the exact set that failed to legalize or a PKM file that failed legalization or adequate information so that we may quickly replicate the parsing behavior on our end. Also specify if any trainerdata was being used.

**Expected behavior**

**Screenshots**
If applicable, add screenshots of Plugin Settings help explain your problem.

**Additional context**

**Comment by architdate** [comment]
Can you post the set here instead of it being the title of a GitHub issue?

**Comment by Rattler2** [comment]
oh sorry new too this didnt know what i was doing :) Garchomp (M) @ Life Orb  
Ability: Rough Skin  
EVs: 4 HP / 252 Atk / 252 Spe  
Jolly Nature  
- Iron Head  
- Earthquake  
- Dragon Rush  
- Brick Break

**Comment by GriffinG1** [comment]
What game are you trying to import this set to?

**Comment by architdate** [comment]
Donphan (M) @ Figy Berry 
Ability: Sturdy 
EVs: 252 Atk / 4 Def / 252 SpD 
Relaxed Nature 
IVs: 0 Spe 
- Counter 
- Gunk Shot 
- Play Rough 
- Body Slam

**Comment by architdate** [comment]
Posting here for investigation later

**Comment by Lusamine** [comment]
Set isn't legal in BDSP (doesn't learn Gunk Shot) or SWSH (doesn't exist), so fails as expected.
Works fine in SM/USUM/XY/ORAS.
Probably a user issue.
