### ISSUE TITLE
Import with Auto Legality Mod error

### ISSUE THREAD

**Issue by Wanderer1391** [architdate/PKHeX-Plugins#12]
On the latest commits when using Import with Auto-Legality Mod to import a set the plugin instead gives an error.
[Import with Auto Legality Mod error.txt](https://github.com/architdate/PKHeX-Plugins/files/3032007/Import.with.Auto.Legality.Mod.error.txt)

**Comment by architdate** [comment]
Are you using the latest release or latest commit of pkhex?

**Comment by Wanderer1391** [comment]
I'm using pkhex commit 9e83e13 which was also just released as Update 19.04.02 and pkhex-plugins commit e89d765.
