### ISSUE TITLE
Prioritize Non-Egg Encounters Option

### ISSUE THREAD

**Issue by SteveCookTU** [architdate/PKHeX-Plugins#120]
**Is your feature request related to a problem? Please describe.**
Related to non-level 100 showdown sets not being hyper trained (since not level 100). 

**Describe the solution you'd like**
The best solution for this is to make egg encounters a last resort if configured. PKHeX returns the encounters list with eggs first so reversing the list of encounters when returned seems like a simple solution if the setting is true. Logically this would make almost all encounters non-egg unless the current level doesn't work with the encounters minimum level.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Lusamine** [comment]
Eggs are returned first if possible to provide the most general cases for battle legality.  Other than level 50 which is a downleveled competitive level, if a user specifically asks for a level that is not 100, why should it be assumed hyper trained?

**Comment by SteveCookTU** [comment]
it's less assuming they want it hyper-trained cause of the level but more they want the full effect of 6IVs because they don't state specific IV information. 

For example, someone is going to submit a set without mentioning IV info (so assumed 6IV) and maybe a specific level between 50 and 100 (odd case maybe but I've seen it plenty of times within the past 3 days). In this case, they will receive a pokemon from an egg at the specified level but will not have the proper stats because an IV wouldn't be hyper trained.

With the feature of transferrable egg moves in the newer games, any encounter can legally have egg moves. The only time eggs are necessary are if the level requested is below the lowest possible met level unless there are other things that may cause eggs to be the only valid encounter for a set.

**Comment by SteveCookTU** [comment]
This enhancement is more geared toward end-user preference. The only reason I thought it might be something to add that's not necessarily battle-legality related is because there are already configuration options that aren't necessary for battle purposes such as force matching the specified ball

**Comment by architdate** [comment]
This should now be resolved, you can specify your own encounter order. You don't have to specify all of them. If you just care about having Wild encounters first, set `Slot` as the first value and then delete the rest (or set it however you prefer for generation of pokemon)
