### ISSUE TITLE
Victini

### ISSUE THREAD

**Issue by Te2011** [architdate/PKHeX-Plugins#125]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why impossible sets cannot be legalized. That should be obvious.
If you encounter a legal pokemon that timed out or didn't legalize properly, upload the `error_log.txt` file present in the same directory as PKHeX

**To Reproduce**
Please provide the exact set that failed to legalize or a PKM file that failed legalization or adequate information so that we may quickly replicate the parsing behavior on our end. Also specify if any trainerdata was being used.

**Expected behavior**

**Screenshots**
If applicable, add screenshots of Plugin Settings help explain your problem.

**Additional context**

Victini  
Ability: Victory Star  
Level: 10  
EVs: 76 HP / 76 Atk / 76 Def / 76 SpA / 76 SpD / 116 Spe  
Modest Nature  
- Fusion Flare  
- Fusion Bolt  
- Glaciate  
- Charge Beam

**Comment by kwsch** [comment]
Are you trying to import Victini in a game where it does not exist?

**Comment by Te2011** [comment]
ok pkhex pokemon brilliant diamond version no pkemon victini
yes or no

**Comment by kwsch** [comment]
BDSP does not have Victini.

Program cannot legalize something where it is never legal.

**Comment by Te2011** [comment]
### 

- [ ] #1. > [`_****_`](url)

> BDSP does not have Victini.
> 
> Program cannot legalize something where it is never legal.

ok thank you
