### ISSUE TITLE
Gen Smogon Sets still not working

### ISSUE THREAD

**Issue by BeyondTheHorizon** [architdate/PKHeX-Plugins#13]
Hi, I decided to talk openly about the "Gen Smogon Sets" again since #9 all the back in January, as it still isn't working for me.

Trying to gen Smogon Sets from Gens 1 and 2 results in the following error.

![error](https://user-images.githubusercontent.com/20503303/57862175-d66f0580-77ef-11e9-9785-c07665b9fc4f.png)

Trying to gen Smogon Sets from Gen 3-7 results in this popup, and it then says the sets are genned but they aren't copied to the clipboard.

![error_2](https://user-images.githubusercontent.com/20503303/57862286-0918fe00-77f0-11e9-8412-adc95943cf05.png)

I apologize for not being open about this until now.

**Comment by architdate** [comment]
Okay can you confirm what pkhex commit are you using? And what plugins commit?

**Comment by BeyondTheHorizon** [comment]
I'm using PKHeX 19.05.15 and PKHeX-Plugins commit cfcd247.

**Comment by architdate** [comment]
Hey, sorry for the late reply, but could you try it on 190402 release of PKHeX? I'll take a look at this none the less

**Comment by BeyondTheHorizon** [comment]
I have now tried it in 19.04.02 and can confirm the error is still there. I really should have spoken about this sooner; I've been having this problem since January.
