### ISSUE TITLE
Pokémon caught in original game flagged as non-legal after weight legality update

### ISSUE THREAD

**Issue by XIKingGoldIX** [architdate/PKHeX-Plugins#134]
**Describe the bug**
A Pokémon caught in the original game (PLA) is flagged as non-legal after the weight legality update. The Pokémon in question is shiny driftblim caught in the original game and then traded to me. I haven't modified the Pokémon at all.

**To Reproduce**
1. Go to Pkhex.exe
2. Load main save file
3. The pokémon is incorectly flagged as non legal

**Expected behavior**
It shouldn't be flagged because its legit caught in-game.
**Screenshots**
![image](https://user-images.githubusercontent.com/97769629/153957245-0f9faa2d-d4dd-4890-81e5-3d492519fbba.png)

**Additional context**
Weirdly enough the weight value for the legal and non-legal pokemon are the same. Only the ones where "Auto" is unchecked for height/weight are considered non-legal

**Comment by Lusamine** [comment]
Nothing to do with this repo.

**Comment by XIKingGoldIX** [comment]
Found a quick fix just to let you know, if you view the flagged pokémon in-game by getting it out of the pokéball and then putting it back in the pokéball, save the game and load the save file in pkhex. The flag will disappear by itself.
