### ISSUE TITLE
pkhex crashing when loading legality mod plugins

### ISSUE THREAD

**Issue by s-zenmode** [architdate/PKHeX-Plugins#137]
**Describe the bug**

pkhex crash when using plugins

**To Reproduce**
1. download pkhex
2. download plugins zip from downloads
3. extract pkhex into a folder and make a subfolder called plugins and extract the dlls into it

**Expected behavior**

I wanted to use legality mod

screenshot:
![image](https://user-images.githubusercontent.com/83439414/155857941-21c9fe5c-1182-40e4-9f18-edc426937181.png)

**Comment by kwsch** [comment]
the error message says it can't run stuff from a network location.

Be sure the zip is unblocked, and you aren't running the program from a network folder like a OneDrive folder.

Try using the setup executables if you still have issues.
