### ISSUE TITLE
Import with Auto-Legality Mod Bug

### ISSUE THREAD

**Issue by Wanderer1391** [architdate/PKHeX-Plugins#14]
Using PKHeX Commit 6e8f7fe and PKHeX-Plugins Commit f6972d3 attempting to use the Import with Auto-Legality Mod option to import a set brings up this error message:

[Exception.txt](https://github.com/architdate/PKHeX-Plugins/files/3200421/Exception.txt)

I assume its the same problem as with #12 in that some code needs an update.

**Comment by architdate** [comment]
Yes the code needs an update. Use the code with the second latest release of PKHeX. The latest release of PKHeX has a bunch of changed functionality which has to be included in the mod still. 

Keeping the issue open till I fix stuff on the mod to work with the latest commit
