### ISSUE TITLE
not working with the last pkhex version (22/05/08)

### ISSUE THREAD

**Issue by Elvundil** [architdate/PKHeX-Plugins#142]
**Describe the bug**
the plugin not working on the last version of pkhex.
it's show this error : 

Exception Details:
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.TypeLoadException: Impossible de charger le type 'PKHeX.Core.PKMConverter' à partir de l'assembly 'PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   à PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   à PKHeX.Core.AutoMod.APILegality.<>c__DisplayClass94_0.<GetLegalFromTemplateTimeout>g__GetLegal|0()
   à System.Threading.Tasks.Task`1.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PKHeX.Core.AutoMod.APILegality.<TimeoutAfter>d__96.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   à PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplateTimeout(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   à PKHeX.Core.AutoMod.Legalizer.Legalize(ITrainerInfo tr, PKM pk)
   à AutoModPlugins.LegalizeBoxes.LegalizeActive()
   à System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   à System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ToolStrip.WndProc(Message& m)
   à System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Exception interne #0) System.TypeLoadException: Impossible de charger le type 'PKHeX.Core.PKMConverter' à partir de l'assembly 'PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   à PKHeX.Core.AutoMod.APILegality.GetLegalFromTemplate(ITrainerInfo dest, PKM template, IBattleTemplate set, LegalizationResult& satisfied)
   à PKHeX.Core.AutoMod.APILegality.<>c__DisplayClass94_0.<GetLegalFromTemplateTimeout>g__GetLegal|0()
   à System.Threading.Tasks.Task`1.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PKHeX.Core.AutoMod.APILegality.<TimeoutAfter>d__96.MoveNext()<---

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=22.5.8.0, Culture=neutral, PublicKeyToken=null
E:\Téléchargements\Game3DSWIIPC\PokeGenfull\pKHeX util\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll

System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll

System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.dll

System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Extensions.dll

Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll

System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll

System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll

PKHeX.Drawing.PokeSprite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=fr, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_fr_b77a5c561934e089\System.Windows.Forms.resources.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Drawing.Misc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
E:\Téléchargements\Game3DSWIIPC\PokeGenfull\pKHeX util\plugins\AutoModPlugins.dll

PKHeX.Core.Injection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Overworld8Searcher, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
E:\Téléchargements\Game3DSWIIPC\PokeGenfull\pKHeX util\plugins\Overworld8Searcher.dll

QRPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
E:\Téléchargements\Game3DSWIIPC\PokeGenfull\pKHeX util\plugins\QRPlugins.dll

PKHeX.Core.AutoMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
An error occurred while listing the Loaded Assemblies:
System.NotSupportedException: Le membre appelé n'est pas pris en charge dans un assembly dynamique.
   à System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   à PKHeX.WinForms.ErrorWindow.UpdateExceptionDetailsMessage()
--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
![pkhexplugin error](https://user-images.githubusercontent.com/79280679/167378449-fc71c830-5156-4928-bf43-95ee6e7b0fce.png)

**Comment by Lusamine** [comment]
Don't mismatch versions.  This isn't a bug but expected behavior.  Every release has a PKHeX that it is intended for.

Read this part of the wiki and wait for a release if you want to use it on the latest PKHeX.
https://github.com/architdate/PKHeX-Plugins/wiki/Installing-PKHeX-Plugins#installing-older-releases

**Comment by Doctor-Pokemon** [comment]
...or get the latest version from Azure Pipeline?
That's what I did, and it's working flawlessly with PKHeX (05-08-22).

**Comment by Lusamine** [comment]
> ...or get the latest version from Azure Pipeline? That's what I did, and it's working flawlessly with PKHeX (05-08-22).

Sure, this is also an example of "not mismatching versions".  You can go as far back or as far forward as you want as long as you're on the same version.

The latest commit still has a few bugs, but upgrading both to unstable will get around the problem in the issue too. If you're using stable releases, the number must match.

**Comment by Doctor-Pokemon** [comment]
Yeah.
In retrospect, my comment was kinda superfluous, and I didn't even notice this issue was closed.
I'm sorry.
