### ISSUE TITLE
Implement task cancellation 

### ISSUE THREAD

**Issue by FM1337** [architdate/PKHeX-Plugins#148]
**Is your feature request related to a problem? Please describe.**
If Auto Legality gets stuck trying to bruteforce, it will begin hogging CPU threads for each thread it spins up for each legality attempt. See: https://www.youtube.com/watch?v=gVdb9L8d7HQ

**Describe the solution you'd like**
According to Kurt, this issue is caused by the lack of task cancellation implementation
![image](https://user-images.githubusercontent.com/5448220/190789901-b51fc3bb-d68f-470b-892c-1f1a7a4897a3.png)
So, assuming that it is possible, I would like to request that task cancellation be implemented so that the legalizer can be stopped after a certain period of time to avoid hogging CPU usage. 

**Describe alternatives you've considered**
The work around I did for CoreAPI, was to write a bash script to be run every minute to check the CPU usage, and if it was high enough, it would restart the CoreAPI docker container as the assumption was that CoreAPI was stuck on trying to legalize a Pokemon that clearly could not be legalized.

**Additional context**
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation

So when I tried to implement task cancellation on CoreAPI (back when I assumed that the problem could be fixed on my end) I believe it was said that task-cancellation would not work on Linux. I'm not sure if that was exactly the same thing, it could've been something different, or if it was the same thing, I'm not sure if it's still the case.

**Comment by nerd40** [comment]
one drive error. any ways to get aroud it? i also uninstalled it

**Comment by architdate** [comment]
Handled privately over discord
