### ISSUE TITLE
Disabling OneDrive help  

### ISSUE THREAD

**Issue by C1043r** [architdate/PKHeX-Plugins#150]
I need a guide to disable Onedrive to open: almsetup_stable

Source: https://github.com/architdate/PKHeX-Plugins/releases

**Comment by architdate** [comment]
Hey, please refer to a guide that disables syncing folders with one drive. You can refer the wiki for further issues or google answers regarding this.

here is a website that explains how to unlink/exclude or remove folders from one drive https://www.thewindowsclub.com/how-to-remove-a-folder-from-onedrive

Hope this helps :)

**Comment by C1043r** [comment]
Thank you very much for your help! It finally worked!
