### ISSUE TITLE
Any help? this pops up everytime i try to legalize a pokemon. 

### ISSUE THREAD

**Issue by HungryAlien** [architdate/PKHeX-Plugins#151]
**Describe the problem**
A clear and concise description of what the bug is. This is not to ask why impossible sets cannot be legalized. That should be obvious.
If you encounter a legal pokemon that timed out or didn't legalize properly, upload the `error_log.txt` file present in the same directory as PKHeX

**To Reproduce**
Please provide the exact set that failed to legalize or a PKM file that failed legalization or adequate information so that we may quickly replicate the parsing behavior on our end. Also specify if any trainerdata was being used.

**Expected behavior**

**Screenshots**
If applicable, add screenshots of Plugin Settings help explain your problem.

**Additional context**

**Comment by kwsch** [comment]
Do not mix and match old & new versions of plugins and PKHeX.exe

Old plugins will not always be compatible with new releases. Wait for the plugin to be updated, or use an older release of PKHeX that the plugin targets.
