### ISSUE TITLE
Skip download PKHeX

### ISSUE THREAD

**Issue by hasban12138** [architdate/PKHeX-Plugins#153]
HI, For some reason China's network can not download PKHeX by almsetup_stable,and then get stuck . So it has some way to skip download PKHeX?
![image](https://user-images.githubusercontent.com/33484052/204554679-9df1f042-385a-431d-a844-f04cb0bb4b05.png)

Thanks!

**Comment by Lusamine** [comment]
The website was flagged for spam about a month ago so some ISPs are still blocking it. You can download the latest stable release of PKHeX from here:

https://cdn.discordapp.com/attachments/679178558597496872/1046267430344863775/PKHeX_221126.zip

Can you tell us what your internet service provider is so Project Pokemon can reach out to them to try and appeal?

**Comment by hasban12138** [comment]
Thanks! 
I can use this link to download, and I can also enter the official website, but I can’t download it using the script.
I already have PKHeX, will this script download anything other than PKHeX?

**Comment by Lusamine** [comment]
The script downloads the plugins and sets them up correctly for you. If you can't run the script, you can follow the Wiki for manual installation. Remember to unblock the plugins.

If you can access the site, that doesn't sound like the usual ISP problems.

**Comment by hasban12138** [comment]
Thanks!
