### ISSUE TITLE
Option to restore Tera Orb charge on demand

### ISSUE THREAD

**Issue by DaWoblefet** [architdate/PKHeX-Plugins#154]
**Is your feature request related to a problem? Please describe.**
When doing solo mechanics tests in the overworld, you have to constantly heal at a Pokemon Center to restore your Tera Orb to terastallize again. This is somewhat slow.

**Describe the solution you'd like**
I would like a quick option on the LiveHex UI to instantly restore the player's Tera Orb charge without needing to go heal.

**Describe alternatives you've considered**
Healing at centers is a bit faster than soft resetting. Testing mechanics with another person is of course faster, but not always available.

**Additional context**
Love the program; it's working very well for me in SV!

**Comment by Lusamine** [comment]
This needs to be documented in order to be edited. Once it is understood how to edit this, then an editor can be made.
