### ISSUE TITLE
Import for showdown works with blank lines or spaces but Import for ALM does not

### ISSUE THREAD

**Issue by k20stitch** [architdate/PKHeX-Plugins#155]
**Describe the bug**
This fails
```
Ditto @ Gold Bottle Cap

Level: 100

Ability: Imposter
```
This does not
```
Ditto @ Gold Bottle Cap
Level: 100
Ability: Imposter
```

**To Reproduce**
Import the following form clipboard into ALM
```
Ditto @ Gold Bottle Cap

Level: 100

Ability: Imposter
```

**Expected behavior**
Blank lines should be stripped (similar to showdown import)

**Comment by k20stitch** [comment]
Unaware you could import sets. If I export a team via smogon and import set
using showdown import it only ever pulls the first monster.

**Comment by Lusamine** [comment]
Showdown doesn't interpret the set with too many blank lines in it as a team import.

![image](https://user-images.githubusercontent.com/30205550/207758695-38f8c955-ba21-44be-9ab4-fe4b2e878142.png)
![image](https://user-images.githubusercontent.com/30205550/207758716-4a72684c-e73f-41e3-955e-fe6d2fbffb49.png)

**Comment by architdate** [comment]
I think then I would keep functionality as it is since it is infeasible to determine when a new pokemon starts in a multiline import

**Comment by k20stitch** [comment]
I'll see if I can come up with anything clever. Could you direct me to
the file name responsible for this crash?
