### ISSUE TITLE
FR: Set all possible Technical Records upon creation

### ISSUE THREAD

**Issue by ankushg** [architdate/PKHeX-Plugins#157]
**Is your feature request related to a problem? Please describe.**
When generating a pokemon, it's great that the ALM already can give it all possible marks. 

It would be _also_ great if it had all applicable TM/HMs already marked as learned, to make it easier to switch between movesets -- especially in S/V where we can't just buy TMs.

**Describe the solution you'd like**
- option in ALM plugin settings under Customization to `SetAllTechnicalRecords`
- automatically mark all legal TMs as learned for the given pokemon

**Comment by kwsch** [comment]
Use the batch command to set all as an extra instruction for the showdown set.

```
.Relearn=$suggestAll
```
