### ISSUE TITLE
Legalize ditto

### ISSUE THREAD

**Issue by k20stitch** [architdate/PKHeX-Plugins#158]
Ditto and ALM in Gen. 9.

One of the more popular requests are 6IV ditto. 6 real perfect IV. It’s important to mention real IV because IVs maxed out with super training are not passed down via breeding.

for whatever reason, the legality mod always defaults to the static ditto encounter which cannot have perfect IVs.

for most other Pokémon, the met as an egg usually has priority, followed by wild encounter, then static, at least from my experience.

**Comment by Lusamine** [comment]
The mod is designed for battle legality, which is fine with Hyper-Trained Ditto.

If you want to target another encounter type, see the Wiki > Plugin Settings to learn how to PrioritizeEncounter.
