### ISSUE TITLE
LiveHex Block Editor not working in Violet

### ISSUE THREAD

**Issue by nefariouslegion** [architdate/PKHeX-Plugins#159]
**Describe the bug**
I'm trying to use the LiveHex Block Editor to change the number of certain items in my bag but it does not work, I open the block editor, find the item I want to modify the quantity of, change the quantity, click save. Nothing happens in game though. The quantity does not change.

**To Reproduce**
1. Go to 'LiveHex Block Editor'
2. Click on 'Edit Block'
3. Scroll down to 'whatever item you want to change the quantity of'
4. Change the quantity
5. Click save
6. Check if game reflects changed quantity

**Expected behavior**
The quantity in-game should change

**Screenshots**

**Additional context**

**Comment by architdate** [comment]
Working as intended, you need to save and restart the game after live edits

**Comment by nefariouslegion** [comment]
Ohhh that's what I was doing wrong. Thank you for the quick reply!
