### ISSUE TITLE
LiveHeX: Box operations do not complete properly

### ISSUE THREAD

**Issue by soopercool101** [architdate/PKHeX-Plugins#160]
**Describe the bug**
Box operations (Clear, sort, etc.) do not properly work in LiveHeX

**To Reproduce**
1. Open LiveHeX
2. Right Click the Box tab
4. Click an operation (ie Clear)
5. Switch off the box, then back to it

**Expected behavior**
Operation should work and be reflected both in-game and in-editor. Sort operations may be beyond scope for live editing but mass-deletion operations would be useful to have.

**Screenshots**
![PKHeX_bfJnS9qtgs](https://user-images.githubusercontent.com/35675593/210417316-c039dd18-9119-459d-8d5c-1c4cbff0772b.gif)

**Comment by Lusamine** [comment]
Not a bug.  LiveHeX doesn't write entire boxes.

Refer to the wiki for how to manually write an entire box: https://github.com/architdate/PKHeX-Plugins/wiki/Installing-LiveHeX
