### ISSUE TITLE
SID is changed when using Trainerdata.txt

### ISSUE THREAD

**Issue by coolbond1** [architdate/PKHeX-Plugins#161]
**Describe the problem**
When i try to legalize with a filled out Trainerdata.txt file it changes the SID to a complete random SID

**Expected behavior**
The SID should not change otherwise whats the point of adding SID to the data sheet?

**Screenshots**
If applicable, add screenshots of Plugin Settings help explain your problem.
![Before legalization](https://user-images.githubusercontent.com/44048214/211197834-f8a4464a-899d-47ac-a742-97daa7c5d3a2.png)
![After Legalization](https://user-images.githubusercontent.com/44048214/211197866-048a13d1-238b-4a0b-a3eb-6c54430c0756.png)
![Trainerdata.txt file](https://user-images.githubusercontent.com/44048214/211197912-19b04f4d-42ab-41fb-9361-1091e1e46a83.png)
![Settings part 1](https://user-images.githubusercontent.com/44048214/211198060-0e633a56-94f6-4d51-a766-aa0a8e11429c.png)
![Settings part 2, tried to set the override to both true and false but that did not work](https://user-images.githubusercontent.com/44048214/211198087-1df118cd-c28e-4f26-9fdb-24878c1013c4.png)

If needed i can zip up my entire PKHeX folder and post it if it would help figure it out

**Comment by architdate** [comment]
What game are you importing in? Also there is no such thing as trainerdata.txt

Trainerdata is set based on the `trainers` folder you create. Please read here for further clarification https://github.com/architdate/PKHeX-Plugins/wiki/Trainer-Data

Reopen the issue if you are still facing the issue

**Comment by coolbond1** [comment]
Apparently i used a old guide for the setup but i followed the steps you linked and im still having the same issue.

**Comment by architdate** [comment]
if the wingull is made shiny through ShinySID then the SID may change to accomodate for the shininess

**Comment by coolbond1** [comment]
i see, any other way to make it shiny that does not affect sid? all i did was click the star next to PID so if there is another way then i would love to know

**Comment by architdate** [comment]
What game is this in? if its one of the newer games, there wont be a PID correlation and shininess can be based on the PID provided, if its an older game its unlikely to do this while maintaining the other properties of the pokemon.

**Comment by coolbond1** [comment]
its in emerald and i dont really care about the other stuff as i can always use RNG reporter to get a specific stat spread but its a bit slow if im gonna do that for every mon i want shiny.

**Comment by architdate** [comment]
Ah unfortunately then ALM wont make shinies without changing SID because emerald rng correlation is rather complex and ALM prioritizes battle stats over ownership values.

**Comment by coolbond1** [comment]
possibility to add an option to prioritize ownership over stats?

**Comment by Lusamine** [comment]
This was intentionally not done because again, the priority is battle values. It would be fairly annoying to brute force a PID that is shiny at the lower shiny rate back then and also preserve all the battle legality. You would be better off looking up an RNG tool and picking out the PID you want that is shiny for you.
