### ISSUE TITLE
"WARNING: OneDrive is detected on your system. Please move the setup file to a different location before running the program."

### ISSUE THREAD

**Issue by memeizt** [architdate/PKHeX-Plugins#165]
**Describe the bug**
"WARNING: OneDrive is detected on your system. Please move the setup file to a different location before running the program."

**To Reproduce**
1. Go to 'Where the PXHeX setup file is'
2. Click on 'The PKHeX setup file'
3. Scroll down to 'See the message'

**Expected behavior**
For the setup to properly work
**Screenshots**
https://gyazo.com/89a156f61d2c0f01452d99cc05ef5977
**Additional context**

**Comment by architdate** [comment]
I think the warning is fairly straightforward. PKHeX and plugins dont properly work if they are on cloud folders such as one drive. Move the setup to a location that is not in your one drive folder. This is working as expected
