### ISSUE TITLE
About Pokémon with Mightiest Mark

### ISSUE THREAD

**Issue by ppllouf** [architdate/PKHeX-Plugins#169]
How do I get a Pokémon with Mightiest Mark through living Dex.
For example: Charizard with Mightiest Mark,.

**Comment by Lusamine** [comment]
The goal of Living Dex is to have one of each, not to have any special features. Only a handful of Pokemon can have Mightiest Mark so you're better off generating them specifically.

[See Charizard, Cinderace, Greninja](https://www.serebii.net/scarletviolet/teraraidbattleevents.shtml)
