### ISSUE TITLE
Cannot generate living dex for Gen 4 games

### ISSUE THREAD

**Issue by Guezter** [architdate/PKHeX-Plugins#197]
For some reason I'm not able to generate living dex for gen 4 pkmn games. Works fine with ORAS, USUM, S/Sh, BW2 on my end. But for any Gen 4 games I get this error.

Anyone else having this problem or might understand why this is happening?

=> Error report https://pastebin.com/sdzpHqeC

**Comment by InkDragon** [comment]
similar error but for gen 3 games
https://pastebin.com/dNVV7u9J
