### ISSUE TITLE
Cannot generate living dex for SCVI

### ISSUE THREAD

**Issue by teward** [architdate/PKHeX-Plugins#198]
**Describe the bug**
When working in a SCVI file, we are unable to use "Generate Living Dex" in the latest release, and it simply errors out, it seems, without an error message but only generates a Gholdengo and creates nothing else.

**To Reproduce**
1. Open a blank Scarlet/Violet save file.
2. Click on 'Tools > ALM >  Generate living dex'
3. Nothing except a gholdengo (which shows as illegal anyways) is generated.

**Expected behavior**
A full living dex to be generated for SCVI.

**Comment by k20stitch** [comment]
Is this a stable or bleeding edge release? This hasn't been updated for version 1.3.2 officially yet.
