### ISSUE TITLE
Legalize hangs if two unlegalizable Pokemon attempt to be legalized at the same time.

### ISSUE THREAD

**Issue by FM1337** [architdate/PKHeX-Plugins#20]
During the rewrite of CoreConsole to CoreAPI, I ran into the same bug that existed in CoreConsole (which I originally thought was cause by an issue on my end), it seems that trying to legalize two Pokemon that cannot be legalized, at the same time will cause the application/threads to hang and become unresponsive to any further legalization attempts.

Originally I thought if I turned off AllowBruteforce that it would fix it, but the same results happened even if the bool was set to false.

**Comment by architdate** [comment]
Seems like the base pkhex code was not thread safe. Should be fixed via https://github.com/kwsch/PKHeX/commit/c301ce88ab42269420edabe5a90725c2f072ac8c
