### ISSUE TITLE
how do i fix this Plugin error please

### ISSUE THREAD

**Issue by Awetspoon** [architdate/PKHeX-Plugins#205]
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX.Core.LearnSource8SWSH.GetAllMoves(Span`1 result, PKM pk, EvoCriteria evo, MoveSourceType types) in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\LearnSource\Sources\LearnSource8SWSH.cs:line 133
   at PKHeX.Core.LearnGroup8.GetAllMoves(Span`1 result, PKM pk, EvoCriteria evo, MoveSourceType types, LearnOption option) in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\LearnSource\Group\LearnGroup8.cs:line 161
   at PKHeX.Core.LearnGroup8.GetAllMoves(Span`1 result, PKM pk, EvolutionHistory history, IEncounterTemplate enc, MoveSourceType types, LearnOption option) in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\LearnSource\Group\LearnGroup8.cs:line 137
   at PKHeX.Core.LearnGroupHOME.GetAllMoves(Span`1 result, PKM pk, EvolutionHistory history, IEncounterTemplate enc, MoveSourceType types, LearnOption option) in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\LearnSource\Group\LearnGroupHOME.cs:line 139
   at PKHeX.Core.LearnGroup9.GetAllMoves(Span`1 result, PKM pk, EvolutionHistory history, IEncounterTemplate enc, MoveSourceType types, LearnOption option) in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\LearnSource\Group\LearnGroup9.cs:line 128
   at PKHeX.Core.EncounterMovesetGenerator.GetNeededMoves(PKM pk, ReadOnlySpan`1 moves, GameVersion ver, Int32 generation, EntityContext context) in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\Encounters\Generator\Moveset\EncounterMovesetGenerator.cs:line 256
   at PKHeX.Core.EncounterMovesetGenerator.GenerateVersionEncounters(PKM pk, ReadOnlyMemory`1 moves, GameVersion version, Byte generation, EntityContext context)+MoveNext() in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\Encounters\Generator\Moveset\EncounterMovesetGenerator.cs:line 207
   at PKHeX.Core.EncounterMovesetGenerator.GenerateVersionEncounters(PKM pk, ReadOnlyMemory`1 moves, GameVersion version)+MoveNext() in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\Encounters\Generator\Moveset\EncounterMovesetGenerator.cs:line 190
   at PKHeX.Core.EncounterMovesetGenerator.GenerateEncounters(PKM pk, ReadOnlyMemory`1 moves, IReadOnlyList`1 vers)+MoveNext() in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.Core\Legality\Encounters\Generator\Moveset\EncounterMovesetGenerator.cs:line 165
   at PKHeX.WinForms.SAV_Encounters.GetAllSpeciesFormEncounters(IEnumerable`1 species, IPersonalTable pt, IReadOnlyList`1 versions, UInt16[] moves, PKM pk, CancellationToken token)+MoveNext() in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.WinForms\Subforms\SAV_Encounters.cs:line 324
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at PKHeX.WinForms.SAV_Encounters.<>c__DisplayClass28_0.<B_Search_Click>b__0() in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.WinForms\Subforms\SAV_Encounters.cs:line 397
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at PKHeX.WinForms.SAV_Encounters.B_Search_Click(Object sender, EventArgs e) in C:\Users\mratc\Source\Repos\PKHeX\PKHeX.WinForms\Subforms\SAV_Encounters.cs:line 397
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Loaded Assemblies:
--------------------
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Private.CoreLib.dll

PKHeX, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\mratc\Desktop\Pokemon\Hex\PKHeX.dll

System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.dll

System.Threading.Thread, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Threading.Thread.dll

System.Windows.Forms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Windows.Forms.dll

System.ComponentModel.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ComponentModel.Primitives.dll

System.Windows.Forms.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Windows.Forms.Primitives.dll

System.Runtime.InteropServices, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.InteropServices.dll

System.Drawing.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Drawing.Primitives.dll

System.Collections.Specialized, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.Specialized.dll

System.Collections, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.dll

System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Threading.dll

System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.TraceSource.dll

System.Drawing.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Drawing.Common.dll

Microsoft.Win32.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\Microsoft.Win32.Primitives.dll

System.ComponentModel.EventBasedAsync, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ComponentModel.EventBasedAsync.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\Accessibility.dll

System.Resources.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Resources.Extensions.dll

System.Memory, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Memory.dll

System.Drawing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Drawing.dll

System.Numerics.Vectors, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Numerics.Vectors.dll

PKHeX.Core, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\mratc\Desktop\Pokemon\Hex\PKHeX.Core.dll

Microsoft.Win32.SystemEvents, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\Microsoft.Win32.SystemEvents.dll

System.Linq, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Linq.dll

System.Collections.NonGeneric, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.NonGeneric.dll

System.ComponentModel.TypeConverter, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ComponentModel.TypeConverter.dll

System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Text.Json.dll

System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ComponentModel.dll

System.Text.Encodings.Web, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Text.Encodings.Web.dll

System.Text.Encoding.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Text.Encoding.Extensions.dll

System.Runtime.Intrinsics, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.Intrinsics.dll

System.Collections.Concurrent, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.Concurrent.dll

PKHeX.Drawing.PokeSprite, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\mratc\Desktop\Pokemon\Hex\PKHeX.Drawing.PokeSprite.dll

System.ObjectModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ObjectModel.dll

System.Runtime.Loader, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.Loader.dll

System.Private.Uri, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Private.Uri.dll

System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Http.dll

System.Net.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Primitives.dll

System.Diagnostics.Tracing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.Tracing.dll

System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.DiagnosticSource.dll

System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Security.dll

System.Security.Cryptography, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Security.Cryptography.dll

System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Quic.dll

Microsoft.Win32.Registry, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\Microsoft.Win32.Registry.dll

System.Windows.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Windows.Extensions.dll

PKHeX.Drawing, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\mratc\Desktop\Pokemon\Hex\PKHeX.Drawing.dll

PKHeX.Drawing.Misc, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\mratc\Desktop\Pokemon\Hex\PKHeX.Drawing.Misc.dll

System.Threading.ThreadPool, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Threading.ThreadPool.dll

System.Net.Sockets, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Sockets.dll

System.Threading.Overlapped, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Threading.Overlapped.dll

System.Net.NameResolution, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.NameResolution.dll

System.Security.Principal.Windows, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Security.Principal.Windows.dll

System.Security.Claims, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Security.Claims.dll

System.Text.RegularExpressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Text.RegularExpressions.dll

AutoModPlugins, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\mratc\Desktop\Pokemon\Hex\plugins\AutoModPlugins.dll

System.IO.Compression, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.IO.Compression.dll

PKHeX.Core.Injection, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null

TeraFinder.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\mratc\Desktop\Pokemon\Hex\plugins\TeraFinder.Plugins.dll

TeraFinder.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Configuration.ConfigurationManager.dll

System.Xml.ReaderWriter, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Xml.ReaderWriter.dll

System.Private.Xml, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Private.Xml.dll

System.Net.WebClient, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.WebClient.dll

System.Runtime.Serialization.Formatters, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.Serialization.Formatters.dll

System.Xml.XmlSerializer, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Xml.XmlSerializer.dll

System.Reflection.Emit.Lightweight, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Reflection.Emit.Lightweight.dll

System.Reflection.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Reflection.Primitives.dll

System.Reflection.Emit.ILGeneration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Reflection.Emit.ILGeneration.dll

PKHeX.Core.AutoMod, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null

System.Linq.Expressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Linq.Expressions.dll

Microsoft.CSharp, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\Microsoft.CSharp.dll

Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null

System.Diagnostics.Process, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.Process.dll

Octokit, Version=6.0.0.0, Culture=neutral, PublicKeyToken=0be8860aee462442

netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\netstandard.dll

System.Diagnostics.FileVersionInfo, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.FileVersionInfo.dll

System.Diagnostics.StackTrace, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.StackTrace.dll

System.Reflection.Metadata, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Reflection.Metadata.dll

System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.Immutable.dll

System.IO.MemoryMappedFiles, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.IO.MemoryMappedFiles.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by architdate** [comment]
Please give more details such as what set was used and if ur on the latest commit

**Comment by Awetspoon** [comment]
hello so i have rebult pk hex witht the latsest commit. and rebuilt the last commit of the gtp fix that had been done. now i only get this message come up when i use encouter database and search for specific move, gives me the error. 
I also get this error when i exit HexLive.

When i rebuild the lastest commits i get them all pass and rebuild fine. My NUG package is also updated too and made sure evrythings builds without any erros. This problem only occurs when i open hex and use encounter database to search for a specific move oe closing HexLive many thanks
