### ISSUE TITLE
Random IVs when importing from showdown to gen 4 saves. 

### ISSUE THREAD

**Issue by PernelSned** [architdate/PKHeX-Plugins#208]
**Describe the bug**
When a pokemon is imported from showdown to a gen 4 save the IVs are randomized.

**To Reproduce**
1. Go to 'Options, pkhex settings, set default blank save to platinum, pearl or diamond.
2. Import any pokemon from showdown.
3. Look at 'stats' tab
4. See incorrect IVs
5. Repeat import from showdown
6. See randomly different incorrect IVs

**Expected behavior**
IVs should be the same as on showdown.

**Screenshots**
Gastrodon after import:

![Screenshot 2023-08-21 230957](https://github.com/architdate/PKHeX-Plugins/assets/6433867/219ed4e1-ad49-4e64-a5fa-4e9883fd24ce)

**Additional context**
Gastrodon before import:

```Gastrodon-East @ Rindo Berry  
Ability: Storm Drain  
Level: 50  
EVs: 252 HP / 4 Def / 252 SpD  
Impish Nature  
IVs: 0 Spe  
- Recover  
- Curse  
- Waterfall  
- Earthquake
```
Version: RC 23.07.09

**Comment by PernelSned** [comment]
If this is not a bug, is there a way to disable the legality as I am just using ALM to batch import teams from showdown and don't actually need them to be legal, however without using ALM I would have to import each pokemon one by one.

**Comment by architdate** [comment]
This isnt a bug and if you want to import multiple showdown sets without caring about legality then please make an issue in the base PKHeX repository! Thanks
