### ISSUE TITLE
PKHeX 23.08.23 encounter database serach button is missing

### ISSUE THREAD

**Issue by abanash** [architdate/PKHeX-Plugins#209]
Im trying to open up the encounter data base ssection but there is no search button.

<img width="590" alt="image" src="https://github.com/architdate/PKHeX-Plugins/assets/143733698/af587d11-ade6-4fce-9cd0-5e442b973f31">

**Comment by kwsch** [comment]
The program renders 11 rows.

If your screen is too small or you're upscaling the program, you're going to get a form that is too big to display.

Either disable the upscaling, or use a bigger monitor.
