### ISSUE TITLE
(Livehex) Pokémon not loading in game unless I click on them.

### ISSUE THREAD

**Issue by Rino6357** [architdate/PKHeX-Plugins#21]
When I drag a Pokémon into the pkhex boxes, they won’t show up in game, even if I exit the boxes in game and check them back in, but if I click on the Pokémon I inserted into game via Livehex again, they show up. Sometimes the same thing happens but only their sprites aren’t showing but they’re in the box. Sometimes they don’t show up at all.

Sometimes this doesn’t happen but it happens most of the time.

**Comment by architdate** [comment]
"Could not replicate" - Chad Kurt
