### ISSUE TITLE
How to download Pkhex auto legality mod plugin for the latest version of pkhex

### ISSUE THREAD

**Issue by abanash** [architdate/PKHeX-Plugins#210]
I know nothing about coding. So, im looking for assistant on how to dowload the plugin file directly. anyone please help me?

**Comment by kwsch** [comment]
The plugin has not been updated for the latest PKHeX release.

The releases section has the compiled plugin.
https://github.com/architdate/PKHeX-Plugins/releases/tag/23.07.09
