### ISSUE TITLE
Legalize Box instead of 1 pokemon at a time

### ISSUE THREAD

**Issue by Sarutopi21** [architdate/PKHeX-Plugins#213]
Would be nice to have the option to legalizea full box instead of just an active pokemon at a time. I dont know how and if its possible but is just an idea.
Another request would be to be able to have the option legalize active pokemon as a hotkey this way instead of going all the time into tools i can just press the hotkey and its done.

**Comment by architdate** [comment]
Legalizing a box is already possible. Please refer to the wiki to see how :)
