### ISSUE TITLE
IVs are not correctly set on generation - PBR - Gen 4

### ISSUE THREAD

**Issue by FullLifeGames** [architdate/PKHeX-Plugins#219]
When I want to generate Pokémon for Pokémon Battle Revolution (Gen 4), the Pokémon sometimes receives wrong IVs. I think this is related to Hidden Powers or Legendaries.

Reproduce:
* Use a PBR Save: https://drive.google.com/file/d/1USKPY3y1z1qOGcRS6s7ZPhKClnlTFgZV/view?usp=sharing
* Copy an import like the following to your clipboard: https://pokepast.es/2a645cb4154166f3
* "Import with Auto-Legality Mod"
* Manaphy & Latios will have incorrect IVs

**Expected behavior**
I expect the IVs to be set correctly.

**Screenshots**
![image](https://github.com/architdate/PKHeX-Plugins/assets/7888636/78901580-9704-45fc-aa90-23c726ca7a3a)

Thanks for the great work on the Auto-Legality Mod!

**Comment by kwsch** [comment]
There isn't a 6IV0Atk Method 1 spread, so the PIDIV isn't valid. ALM gives you a valid PIDIV as a fallback.

**Comment by FullLifeGames** [comment]
If this is not fixable, I would maybe turn this into a feature request.

Idea: If such a fallback is used, a popup message is shown that states that (leads you to check EVs / IVs).

Currently, it is very easy to miss this and has happened to a couple of friends already.

**Comment by architdate** [comment]
I'll accept this as a feature request. I will add it to the traceback (refer to the DLC branch) that fallback IVs are being used instead of the user provided ones.
