### ISSUE TITLE
Sword/Shield Living dex issue

### ISSUE THREAD

**Issue by Sarutopi21** [architdate/PKHeX-Plugins#224]
Generate living shiny dex is not generating a shiny eternatus, which should be possible.
Shiny Milotic results illigal once Gen8transferTracker is set to Invalid saying that contest stat should be 0.
Weezing is showing as illigal aswell and Mr.Mime (illigal moves) too

**Comment by santacrab2** [comment]
Milotic, Weezing, and Mr.Mime are fixed by setting "AllowHomeTransferGeneration" to False in the plugin settings.

**Comment by architdate** [comment]
Should be fixed on master
