### ISSUE TITLE
ALMSETUP_STABLE

### ISSUE THREAD

**Issue by churtado684** [architdate/PKHeX-Plugins#228]
Everytime i try to run almsetup_stable.exe it gives me the message which is attached. i understand that the PKHeX 23.10.11 doesnt match  the plugin 23.09.25 but it says it is the latest version
![Screenshot 2023-11-10 174234](https://github.com/architdate/PKHeX-Plugins/assets/150490909/af03fb44-db75-484d-a95e-ce28ddc550eb)

**Comment by kwsch** [comment]
Read the bottom half of your screenshot.
