### ISSUE TITLE
I have the latest versions but...

### ISSUE THREAD

**Issue by miguelgargallo** [architdate/PKHeX-Plugins#230]
**Describe the problem**
Versions mismatch while they are in the latest
![image](https://github.com/architdate/PKHeX-Plugins/assets/5947268/48475f0e-24d0-477c-a101-98a9213aab12)

**Comment by kwsch** [comment]
Plugins have not been updated for the latest release, hence the message. Not a bug.

**Comment by miguelgargallo** [comment]
Thanks for your time and patience
