### ISSUE TITLE
Error while trying to build the project from MASTER

### ISSUE THREAD

**Issue by Sarutopi21** [architdate/PKHeX-Plugins#231]
I get this following errors when i try to build the project from the master folder

Severity	Code	Description	Project	File	Line	Column	Suppression State
Error	CS0006	Metadata file 'C:\Users\Lenovo\Desktop\PKHeX-Plugins-master\PKHeX.Core.AutoMod\obj\Debug\net7.0\ref\PKHeX.Core.AutoMod.dll' could not be found	AutoModPlugins	C:\Users\Lenovo\Desktop\PKHeX-Plugins-master\AutoLegalityMod\CSC	1	1	Active

Severity	Code	Description	Project	File	Line	Column	Suppression State
Error	CS0006	Metadata file 'C:\Users\Lenovo\Desktop\PKHeX-Plugins-master\PKHeX.Core.AutoMod\obj\Debug\net7.0\ref\PKHeX.Core.AutoMod.dll' could not be found	AutoModTests	C:\Users\Lenovo\Desktop\PKHeX-Plugins-master\AutoModTests\CSC	1	1	Active

Severity	Code	Description	Project	File	Line	Column	Suppression State
Error	CS0103	The name 'Gigantamax' does not exist in the current context	PKHeX.Core.AutoMod	C:\Users\Lenovo\Desktop\PKHeX-Plugins-master\PKHeX.Core.AutoMod\AutoMod\APILegality.cs	159	26	Active

Severity	Code	Description	Project	File	Line	Column	Suppression State
Error	CS0103	The name 'Gigantamax' does not exist in the current context	PKHeX.Core.AutoMod	C:\Users\Lenovo\Desktop\PKHeX-Plugins-master\PKHeX.Core.AutoMod\AutoMod\Legalization\SimpleEdits.cs	548	17	Active

**Comment by alemany89** [comment]
same here
![image](https://github.com/architdate/PKHeX-Plugins/assets/46443105/deee9425-b5fb-475c-ae7a-b4b1c310e8bd)

**Comment by alemany89** [comment]
nevermind i saw the other branch (net8)

**Comment by Sarutopi21** [comment]
> nevermind i saw the other branch (net8)

did you solve it?

**Comment by edwarbad23** [comment]
> > nevermind i saw the other branch (net8)
> 
> did you solve it? i still get this errors ![error](https://private-user-images.githubusercontent.com/145146494/289355847-8782961a-8779-4344-bf57-30d090248838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTAyNzksIm5iZiI6MTcwMjIwOTk3OSwicGF0aCI6Ii8xNDUxNDY0OTQvMjg5MzU1ODQ3LTg3ODI5NjFhLTg3NzktNDM0NC1iZjU3LTMwZDA5MDI0ODgzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxMjA2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjU2NjE5MGUyODMwZWY1ZjRlMWNkMDUzN2ZmNmEyYTAyYWZjNzY3ZTIxMGM3MWZkMjg3MDM0ODAyMjQ1Yzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eGtoCQVefu-L4ThY98X5JZar6o22y13K4euMR-_Anbs)

In VS change the branch too, right down corner, it's set to master, you must change to net8

**Comment by alemany89** [comment]
i solved it but compiling the net8 branch

**Comment by Sarutopi21** [comment]
> > > nevermind i saw the other branch (net8)
> > 
> > 
> > did you solve it? i still get this errors ![error](https://private-user-images.githubusercontent.com/145146494/289355847-8782961a-8779-4344-bf57-30d090248838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTAyNzksIm5iZiI6MTcwMjIwOTk3OSwicGF0aCI6Ii8xNDUxNDY0OTQvMjg5MzU1ODQ3LTg3ODI5NjFhLTg3NzktNDM0NC1iZjU3LTMwZDA5MDI0ODgzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxMjA2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjU2NjE5MGUyODMwZWY1ZjRlMWNkMDUzN2ZmNmEyYTAyYWZjNzY3ZTIxMGM3MWZkMjg3MDM0ODAyMjQ1Yzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eGtoCQVefu-L4ThY98X5JZar6o22y13K4euMR-_Anbs)
> 
> In VS change the branch too, right down corner, it's set to master, you must change to net8

i cant find anything on the right down corner that says master or net8

**Comment by edwarbad23** [comment]
![cxcx](https://github.com/architdate/PKHeX-Plugins/assets/21049981/cc697545-9f2d-4c52-b7ff-ddba4bd2a05d)
 here
