### ISSUE TITLE
OW8IVsearcher and teraRaidCalculator is too slow

### ISSUE THREAD

**Issue by Matthewliu7** [architdate/PKHeX-Plugins#242]
I want search a 0A0S HT255or0 Cresselia,but it's too slow,about 150t/s,how long will it take to FFFFFFFFFFFFFFFF........

Can I use multithreading calculation by this software?Then I can speed up.

It doesn't look like it's using multiple threads now,even I want search by graphics card..

As you see,Cresselia need shsw and bdsp can shiny and HT255,I want it's valid....

**Comment by kwsch** [comment]
Those aren't a part of this repo.
