### ISSUE TITLE
Request for Updated "Auto-Legalization" Plugin Compatible with Latest Core (2024.11.11)

### ISSUE THREAD

**Issue by SlayerOfTime** [architdate/PKHeX-Plugins#254]
Dear Archidate,

I hope this email finds you well. I am reaching out regarding the "Auto-Legalize" plugin for the PkHeX application. This tool has been an invaluable resource for the plugin user community, and we truly appreciate the effort you have put into its development.

Unfortunately, I recently discovered that the plugin is not compatible with the latest Core version of PkHeX (2024.11.11). 

I would greatly appreciate it if an update could be released to ensure the plugin works seamlessly with this new version. The community would be thrilled to see this update, as it would allow us to continue using PkHeX without any issues.

If you need any additional information or assistance, please do not hesitate to reach out to me.

Thank you in advance for your efforts in maintaining and improving this excellent tool.

Best regards,
Harry

**Comment by kwsch** [comment]
Duplicate: https://github.com/architdate/PKHeX-Plugins/issues/250
