### ISSUE TITLE
Disabling Xoroshiro doesn't affect Eggs

### ISSUE THREAD

**Issue by swampatha** [architdate/PKHeX-Plugins#28]
When having Xoroshiro disabled, it only affects raids. Your TID and SID still gets randomized when requesting a shiny from an egg.

**Comment by architdate** [comment]
xoroshiro doesnt even apply to eggs though. So I couldnt replicate this. Refer to this:
https://github.com/architdate/PKHeX-Plugins/blob/master/PKHeX.Core.AutoMod/AutoMod/APILegality.cs#L520-L529

I don't use xoroshiro anywhere else.
