### ISSUE TITLE
Pokeball legality issue 

### ISSUE THREAD

**Issue by YoshivsJoshi** [architdate/PKHeX-Plugins#31]
Hello, there is an issue with Safari ball pokemon I have tried to make a Safari ball Roserade without it's hidden ability born in Galar, from an egg. it's saying that the pokeball is unobtainable, but you can catch it in the Safari zone and transfer it, thank you for everything :)

**Comment by YoshivsJoshi** [comment]
https://bulbapedia.bulbagarden.net/wiki/Great_Marsh

**Comment by Lusamine** [comment]
This is currently a problem with base PKHeX, which isn't properly validating some of the older gen balls.  The plugin can't make anything that PKHeX considers illegal.

**Comment by architdate** [comment]
Closing this. Should be fixed in base pkhex. @kwsch
