### ISSUE TITLE
PKHeX latest commit does not work with latest commit of PKHeX-Plugins

### ISSUE THREAD

**Issue by webstercharly** [architdate/PKHeX-Plugins#42]
It looks like the PKHeX Core Utils has updated the name of one of their functions.
This means updating the two references in PKHEX-Plugins code of files: `ModLogic.cs` and `SimpleEdits.cs`.

**Before**
`WurmpleUtil.GetWurmpleEC(wIndex);`

**Latest**
`WurmpleUtil.GetWurmpleEncryptionConstant(wIndex);`

Thought I would create this issue in case anybody else was trying to build the latest of PKHeX & PKHeX Plugins.

Tried to open a PR to the branch `webstercharly` and got a 403 on pushing remote.

```
remote: Permission to architdate/PKHeX-Plugins.git denied to webstercharly.
fatal: unable to access 'https://github.com/architdate/PKHeX-Plugins.git/': The requested URL returned error: 403
```

**Comment by architdate** [comment]
you would have to fork and create the branch on your own repo. you were trying to create one on mine. However I am already aware and have fixed this issue on my local repo, so no need to PR. I will push the commit after PKHeX does the DLC release. For now please compile and use [this](https://github.com/kwsch/PKHeX/commit/bfef634a1a9f09f03b6cdb6e08caf6250e8258ab) commit and the mod will work just fine :) 

PKHeX plugins is dependent on the PKHeX core nuget which hasnt been updated to support this method signature change either.

Will keep this issue open and pinned for now, but this will be closed soon enough (Once the new PKHeX for DLC is released). No need to PR
