### ISSUE TITLE
.AbilityNumber Batch Edit Bug

### ISSUE THREAD

**Issue by JRandeezy** [architdate/PKHeX-Plugins#44]
Encountering weird issue with the batch edit .AbilityNumber=4 while using bleeding edge build of PKHex

The way I'm loading the save file is exporting it to my SDcard and loading it up via version 3.7.4 of Checkpoint

After a batch edit this turns all pokemon in PKHex HA which is supposed to happen
But, when I load the save file in game it makes all of the mons have Battle Armour as an ability

I think this may be an issue with something related to the .Ability=4 which would give a mon Battle Armour, maybe the game is reading the information incorrectly.

Double checking and using LiveHex as the other inject method instead shows that within PKHEx the pokemon to have HA but in game they all have battle armour

![image](https://user-images.githubusercontent.com/66005281/85198602-09f05d80-b329-11ea-8aaa-55f1cecc8154.png)

![image](https://user-images.githubusercontent.com/66005281/85198607-170d4c80-b329-11ea-926a-223be6499ba6.png)

**Comment by kwsch** [comment]
When changing abilities, you have to make sure that the actual ability is changed when you change the AbilityNumber. Changing one and not the other often leads to a mismatch, which is illegal.

https://github.com/kwsch/PKHeX/blob/2cdb5d26db117f1d15e7cbfb8c346a778c9fa243/PKHeX.Core/Editing/Bulk/BatchEditing.cs#L497

Use `Ability=$2` to refresh the ability to hidden (0/1 for regular abilities, 2=hidden).
