### ISSUE TITLE
Smogon LC Import

### ISSUE THREAD

**Issue by soopercool101** [architdate/PKHeX-Plugins#50]
Currently all smogon-genned Pokemon default to level 100. Little Cup Pokemon should instead be defaulted to Level 5.

This is not an easy fix as the level data does not appear to be contained in the HTML for this, so the format will have to be tied to the set in some form or another in order to fix. I've been unable to do so thus far from my attempts but will open a PR if I am successful.

**Comment by architdate** [comment]
There is a Level entry in the showdown set that lets you do that. Refer to the image below
![image](https://user-images.githubusercontent.com/17220860/93547039-bbd60f00-f996-11ea-9a24-f1460da40b18.png)

Here if you set the level to level 5, the export will have a line saying `Level: 5` in the export. This should generate a level 5 pokemon through auto legality mod import.

Another tip is that if you change the format to Gen 8 LC on Showdown's teambuilder and the level will be set as 5 automatically. Let me know if this was the issue you were having or if I am misunderstanding the issue!

**Comment by soopercool101** [comment]
The issue in screenshots, to help make my point clearer

![PKHeX_NDPl1FugMx](https://user-images.githubusercontent.com/35675593/93547810-bfc44b80-f91a-11ea-85b0-d09c08cd6a0f.png)
![PKHeX_J7zVNfHF3q](https://user-images.githubusercontent.com/35675593/93547819-c652c300-f91a-11ea-9f1f-6b72cf6d4b26.png)
![image](https://user-images.githubusercontent.com/35675593/93547830-cd79d100-f91a-11ea-8e7a-915ad20d5ff1.png)

**Comment by architdate** [comment]
Oh you mean for smogon imports! Okay. I must not be parsing the level from the src then! Thanks for letting me know! I'll fix this one up soon :)

**Comment by soopercool101** [comment]
Level is found after gender, appears that `"level":0` is used for Little Cup sets, inexplicably

**Comment by soopercool101** [comment]
Notably level, gender, and shinyness are both found in the HTML before the set description, so are not currently loaded by the splitter. This also means that the shiny setting code in the smogon imports is non-functional (though this is a moot point as to my knowledge there are no smogon sets that dictate shiny?)

**Comment by architdate** [comment]
Have you tested this PR already or does this need testing? If it needs to be tested, i'll test and merge after work
