### ISSUE TITLE
SmogonGenner and PKHeX blank save files

### ISSUE THREAD

**Issue by BeyondTheHorizon** [architdate/PKHeX-Plugins#6]
Hi, liking your plugins.

Recently, PKHeX included the ability for users to select a version to load a blank save file in. However, when I run SmogonGenner in a blank save file prior to Gen 7, it still collects the Smogon sets from Gen 7. Am I doing something wrong, or will this need to be worked on?

**Comment by architdate** [comment]
Other generations have not been incorporated for smogon genner. It is however on the TODO list :)

**Comment by BeyondTheHorizon** [comment]
Okay. Thank you for letting me know.

**Comment by architdate** [comment]
has been added in the following commit `[6eaff6c](https://github.com/architdate/PKHeX-Plugins/commit/6eaff6c60b04871ed6d654cf28954d1703279ef2)`
