### ISSUE TITLE
Legalize Active Pokemon not working

### ISSUE THREAD

**Issue by Skullkandy64** [architdate/PKHeX-Plugins#81]
I've tried with numerous pokemon and it does not work.It worked on last build but not this one
PLEASE FIX

**Comment by Lusamine** [comment]
See the Wiki about using Showdown Sets.  Legalize Active Pokémon requires you to have basic knowledge of legality and is not the recommended starting method to use the mod.

**Comment by architdate** [comment]
As @Lusamine pointed out, works as intended. Please ensure you are trying to legalize something that is possible in the first place

![2020-11-29_14-27-11](https://user-images.githubusercontent.com/17220860/100534902-fee21780-324e-11eb-9461-30ce75e8c976.gif)
