### ISSUE TITLE
We hope to add some plug-in functions, such as one button self ID, one key random PID, including star flash and square flash, and add one key move record and one button legal medal

### ISSUE THREAD

**Issue by shenhongtao1314** [architdate/PKHeX-Plugins#83]
We hope to add some plug-in functions, such as one button self ID, one key random PID, including star flash and square flash, and add one key move record and one button legal medal

**Comment by kwsch** [comment]
Shortcuts already exist in the main program without the need for plugins.

Shift/Control click the shiny button for the different shiny types.

Click anywhere within the moves groupbox to apply legal moves.

Shift click the give all ribbons button to give all legal ribbons.

Shift click the Technical Records button to give all legal TR flags.

**Comment by shenhongtao1314** [comment]
Can't flash in batches and become legal eggs in batches, and can't learn legal moves in batches.

**Comment by Lusamine** [comment]
Look up how to use the Batch Editor -- also a base program feature.

**Comment by shenhongtao1314** [comment]
I see that pkhex customs plug-ins have these functions, which directly set shortcut keys, which will be more convenient compared with.
