### ISSUE TITLE
Official smogon melmetal toxic set not legalizing

### ISSUE THREAD

**Issue by Wolfling1** [architdate/PKHeX-Plugins#85]
**Describe the problem**
An official smogon melmetal toxic set is not legalizing.

Melmetal @ Leftovers
Ability: Iron Fist
EVs: 252 Atk / 244 SpD / 12 Spe
Adamant Nature
- Protect
- Double Iron Bash
- Earthquake
- Toxic

https://www.smogon.com/dex/ss/pokemon/melmetal/

Even just trying to inject a set with only toxic and no other moves fails
Doing a google search says that melmetal can learn toxic in lets go.

**To Reproduce**
Melmetal @ Leftovers
Ability: Iron Fist
EVs: 252 Atk / 244 SpD / 12 Spe
Adamant Nature
- Protect
- Double Iron Bash
- Earthquake
- Toxic

**Expected behavior**
I expected the set to legalize

**Screenshots**

**Additional context**
Error log is this

[Invalid] [DateTime: 12/31/2020 5:23:27 PM]
Melmetal @ Leftovers
EVs: 252 Atk / 244 SpD / 12 Spe
Ability: Iron Fist
Adamant Nature
- Protect
- Double Iron Bash
- Earthquake
- Toxic

**Comment by architdate** [comment]
This is a base PKHeX issue, we are still ironing out the bugs for the new rewrite. The latest PKHeX commit fixes this already
