### ISSUE TITLE
rebuild no work !!

### ISSUE THREAD

**Issue by arceuss** [architdate/PKHeX-Plugins#91]
![image](https://user-images.githubusercontent.com/28229451/106800911-4e154180-661e-11eb-8614-6493c543f2af.png)

**Comment by kwsch** [comment]
The current commits are targeting a yet-unreleased PKHeX.Core NuGet build.

Use the latest release, or wait until the next one is posted.

**Comment by arceuss** [comment]
i cant even use it on latest pkhex tho

**Comment by Lusamine** [comment]
> 
> 
> i cant even use it on latest pkhex tho

Read the instructions.  Latest release states the version of PKHeX you need.
Either download the old version or wait for a release.
