### ISSUE TITLE
I would like to ask how to change the BID, SID, name and pokemon language

### ISSUE THREAD

**Issue by shenhongtao1314** [architdate/PKHeX-Plugins#97]
I would like to ask how to change the BID, SID, name and pokemon language

**Comment by shenhongtao1314** [comment]
After one click, the sprite will be displayed in Chinese format. Bid, Sid and name are all what you want, and you don't need to modify them

**Comment by architdate** [comment]
This is already a part of the mod.

For TID and SID, you can always use the `trainers` folder. You can read about how to use that here: https://github.com/architdate/PKHeX-Plugins/wiki/Trainer-Data

Alternatively you could use the ALM enhanced showdown set format to import your set and include Language, TID and SID. You can read about how to modify those here:
https://github.com/architdate/PKHeX-Plugins/wiki/ALM-Showdown-Sets

An example set that would work would be as follows:
```
Scorbunny @ Life Orb
Ability: Libero
Level: 5
Shiny: Star
Ball: Poke Ball
Language: Japanese
OT: Jotaro
OTGender: Male
TID: 444444
SID: 1111
EVs: 116 HP / 188 Atk / 204 Spe  
Jolly Nature  
- Blaze Kick  
- Sucker Punch  
- Gunk Shot  
- High Jump Kick
```
