### ISSUE TITLE
Cannot generate living dex for HGSS

### ISSUE THREAD

**Issue by malvarenga123** [architdate/PKHeX-Plugins#98]
**Describe the bug**
The following error appears after a minute or so when trying to generate a living dex for HGSS:
https://pastebin.com/64P5gX6r

**To Reproduce**
1. Have Blank Save Version set to: HeartGold
2. Open PKHeX 20210401 with PKHeX-Plugins RC 21.04.01
3. Click on Tools->Auto-Legality Mod->Generate Living Dex
4. Wait over a minute
5. See the error above

**Expected behavior**
All boxes should be filled with a living Pokédex including all species available in the loaded save file.

**Comment by Lusamine** [comment]
Can't replicate this.
![livingdex](https://user-images.githubusercontent.com/30205550/113360814-1cfc7900-9310-11eb-92c5-3c0b0d61ebf6.gif)

**Comment by malvarenga123** [comment]
Do you have a link to your version (d-20210401)? I'm assuming it's a debug version

**Comment by Lusamine** [comment]
I built from the latest commit here:
![image](https://user-images.githubusercontent.com/30205550/113361220-115d8200-9311-11eb-974b-68b06f228f1e.png)
Did you download from the Releases page or run alm_setup.exe?

**Comment by malvarenga123** [comment]
I downloaded from here: https://projectpokemon.org/home/files/file/1-pkhex/

**Comment by Lusamine** [comment]
The automatic build for latest commit for PKHeX is located at https://projectpokemon.org/home/files/file/2445-pkhex-development-build/, but this is generally not recommended for use with stable releases of plugins.

**Comment by Lusamine** [comment]
I was able to replicate this by removing my `trainers` folder.  Running a living dex on a clean install with alm_setup.exe causes this error, and adding `trainers` folder to it fixes it. Is this your situation?

**Comment by malvarenga123** [comment]
I didn't have a `trainers` folder and creating an empty one doesn't fix it either. Was your folder empty?
Tried with the latest development build and the error persists.

**Comment by Lusamine** [comment]
No, I have proper gen 4 trainer data in there for HGSS.

**Comment by malvarenga123** [comment]
Setting `UseTrainerData` to false, does fix the issue.

**Comment by architdate** [comment]
The latest commit should allow this to work. Issue was with the default fallback being reverted to Gen 7/8 which probably generated pk with format > 4. This should also be fixed in the latest commit 👍

**Comment by Lusamine** [comment]
The release has been hotpatched with the fix:
https://github.com/architdate/PKHeX-Plugins/releases/tag/21.04.01
